### ISSUE TITLE
Is there a way to run normal .feature files not json format with zero code ?

### ISSUE THREAD

**Issue by santoshreddy17** [authorjapps/zerocode#128]
```
@Order
Feature : Blah
    Background: blah1
      Given step1
      And step2
   Scenario: scenario 1
    When i do something
    Then i expect something
```

**Comment by dinesh76in** [comment]
This is actually a deviation from what `Zerocode` does or intended to to. 

Basically, the intention of Zerocode lib is to `keep it simple and neat` and not to spend(waste) too much time in framing the sentences/grammars to satisfy a tool. The tester/developer should spend more time in testing and be able to `easily come up` with executable scenarios(also building up the regression pack)

Anyways the **multi-step** approach can be achieved by the simple JSON steps by `chaining` them via their request/response `JSON Paths`.

We do not see any benefits, but there are `tools/libraries` available in market which already support the `feature files`. You can choose an open-source for your project need(if that's what you are looking for).

**Comment by aghorpade** [comment]
@santoshreddy17  - you can try other opensource framework which works on feature file. zerocode is meant to keep it simple. User doesn't need to know what is feature file and how he has to write given,when,then. 
For technical solution to your problem. consider below zerocode json test which is similar to your feature file steps -
`{
    "scenarioName": "Invoke the GET api and assert the response",  **-- feature -blah**
    "steps": [
        {
            "name": "get_user_details",  **-- step name, background**
            "url": "https://api.github.com/users/octocat",
            "operation": "GET",  **-- scenario1 when**
            "request": {   **-- scenario1 given**
            },
            "assertions": {  **--then expected**
                "status": 200,
                "body": {  
                    "login" : "octocat",
                    "id" : 33847731,
                    "type" : "User"
                }
            }
        }
    ]
}`

I hope this will help you.

**Comment by authorjapps** [comment]
@santoshreddy17 , if you are looking for existing `Given-When-Then` TCs to run via `Zerocode`, then I think you might have to migrate them to Zerocode manually or via writing a script as @aghorpade suggested the mappings.

Otherwise sometimes they might become overly complicated, when the project/test-cases **grow**.

A `GIVEN-WHEN-THEN-AND` can take different shape and developers/testers spend too much time fitting the `AC/User-Journey` into the actual test. 

e.g. <br/>
~~GIVEN- the GitHub REST api GET end point,~~ <br/>
~~WHEN- I invoke the API,~~ <br/>
~~THEN- I will receive 200(OK) status with body and assert the response~~ <br/>

or

~~GIVEN- the GitHub REST url and the method GET,~~ <br/>
~~WHEN- I invoke the API,~~ <br/>
~~THEN- I will receive 200(OK) status with body~~ <br/>
~~AND assert the response~~ <br/>

or

~~GIVEN- the GitHub REST url http://api.github.com/abcd~~ <br/>
~~AND the http method GET~~ <br/>
~~WHEN- I invoke the API using a HTTP client,~~ <br/>
~~THEN- I will receive 200(OK) status with body~~ <br/>
~~AND assert the response~~ <br/>

> and so on...

**Note**- Too much is going on around an `user journey` in writing correct sentences or **nearly** correct sentences to come up with a test case. 

I think we should go for a simpler approach to maintain our test suites and choose any tool accordingly.
