### ISSUE TITLE
Migrating postman rest client scripts to zerocode json stesps

### ISSUE THREAD

**Issue by BeTheCodeWithYou** [authorjapps/zerocode#157]
It will be nice to generate zerocode json steps directly from postman test scripts.

**Comment by aghorpade** [comment]
Generate Zerocode steps from postman - this needs integration with Postman to support zerocode framework for code snippet generation.  It will be a advance feature for zerocode framework and it might take more time to have it

**Comment by santhoshTpixler** [comment]
There is a possibility of converting the **postman collections** into **zerocode** scenarios. But it is not recommended.  Because **postman** already has multiple versions in their exported collection format. You will have to save the response as an example otherwise only request will be exported. I haven't seen an option to export the postman tests yet. Even if we do it, still it won't be making our life easier. 

Let's assume we have converted **Postman** collection into **zerocode** compatible JSON, still, we need to insert the assertions and the file paths(This is a long debated postman issue which won't be fixed any time soon). 

For maintaining the piece of converter code we need to be in sync with the **postman** and that's not a good idea. Still, there are people who are using alternative to postman like the open source one [Insomnia](https://insomnia.rest/) will not be able to use it.

**Comment by santhoshTpixler** [comment]
Since #172  is making progress let's close this.
