### ISSUE TITLE
Cannot resolve io.confluent:kafka-avro-serializer:5.1.0 in V1.3.0 from gradle?

### ISSUE THREAD

**Issue by ashoksl** [authorjapps/zerocode#196]
Repositories not able to resolve io.confluent:kafka-avro-serializer:5.1.0 library from gradle. Am I the only person facing this issue ?

With 1.2.18 also facing the same issue. 

<img width="461" alt="screenshot 2019-02-01 at 10 52 33 am" src="https://user-images.githubusercontent.com/3805973/52104249-8fc61880-260f-11e9-87df-3909b66bc727.png">

**Comment by authorjapps** [comment]
That's because the `lib` is not published to the maven nexus central. You need to point to the confluent nexus. This lib was built by the confluent team and seems like they maintain it in their nexus.

You can resolve this in number of ways.
See here >> https://stackoverflow.com/questions/43488853/confluent-maven-repository-not-working

**Comment by ashoksl** [comment]
Okay. Thanks
