### ISSUE TITLE
Can the producer send a message with a unique id and the consumer can assert the message with the same id?

### ISSUE THREAD

**Issue by tghani93** [authorjapps/zerocode#220]
Hi, I have a couple of questions regarding the framework and your comments / assistance would be highly appreciated.

1. When testing in real environment, there will be multiple messages flowing through the brokers/topics. How can zerocode validate/asset a specific response? 
2. Can the producer send a message with a unique ID and the consumer can assert the message with the same ID? 

Basically how can the framework can differentiate the test message from the production work load.

Regards,
Tabish

**Comment by authorjapps** [comment]
Hello mate, one of us will look into this soon.

**Comment by tghani93** [comment]
I really appreciate it. We would love to use Zerocode for our project, just trying to figure out is it possible to use Zerocode in the scenario of asserting a specific message (with unique ID / key) when multiple messages are being produced to a single topic.

**Comment by authorjapps** [comment]
_Sounds cool!
That means you are taking a very high flight and going to escape all the testing hassles!_

Coming to the issues-

> 2) Can the producer send a message with a unique ID and the consumer can assert the message with the same ID?

Are you referring to the unique message's ID which is the `key` of the record
or
are you thinking about consumer `client.id` ?

Both are easy and possible. Just trying to understand your use-case before providing solution or an example.

> 1) When testing in real environment, there will be multiple messages flowing through the brokers/topics. How can zerocode validate/asset a specific response?

Ans: Use `Json Path` to look for a perticular message or a record key or value. Very easy!
e.g.
When you have consume multiple records from a topic, that means you receive an array of records as the response.
Then you can assert [this way](https://github.com/authorjapps/zerocode#step-dealing-with-arrays) explained in the readme-file.

**Comment by dinesh76in** [comment]
Hello @tghani93, It's worth looking at this [DZone page](https://dzone.com/articles/a-quick-and-practical-example-of-kafka-testing) - Has step by step details for Kafka testing using zerocode.

**Comment by tghani93** [comment]
Thanks for the pointers above, guys.

**1. Can the producer send a message with a unique ID and the consumer can assert the message with the same ID?**
__Are you referring to the unique message's ID which is the key of the record
or
are you thinking about consumer client.id ?_

Both are easy and possible. Just trying to understand your use-case before providing solution or an example._

**Pretty much both. Use case goes like this:

We want to test this in a real environment(it could be pre-prod/prod), that means we expect this tool to identify the test messages among the other traffic within kafka brokers
If there are heaps of messages already flowing through and if we run zerocode to assert one particular message in the pool/topic, will it work ? Does zerocode magically map the response message for a particular test scenario to assert ?
If yes, how ?**

**2. When testing in real environment, there will be multiple messages flowing through the brokers/topics. How can zerocode validate/asset a specific response?
Ans: Use Json Path to look for a perticular message or a record key or value. Very easy!
e.g.**

When you have consume multiple records from a topic, that means you receive an array of records as the response.
Then you can assert this way explained in the readme-file.

_Where is this JSON path is applied ? In JUNIT or within Zerocode JSON config ?_

For example, my test below keeps on failing. In the log, instead of just consuming the messages with the ids I have specified below. It consumes the whole array of 10 messages.

`{
    "scenarioName": "consume a JSON message with id_5 & id_9 out of 10 messages produced on topic_A",
    "steps": [

        {
            "name": "consume_step",
            "url": "kafka-topic:topic_A",
            "operation": "consume",
            "request": {
                "consumerLocalConfigs": {
                    "recordType": "JSON",
                    "commitSync": true,
                    "showRecordsConsumed": true,
                    "maxNoOfRetryPollsOrTimeouts": 3
                }
            },
            "assertions": {
                "records": [
                    {
                        "key": "id_5",
                        "value": {

                            "TEST": "Test Val0"
                        }
                    },
                    {
                        "key": "id_9",
                        "value": {

                            "TEST": "Test Val9"
                        }
                    }
                ]
            }
        }
    ]
}
`

**Comment by nirmalchandra** [comment]
Hello mate @tghani93 ,

Just to set the contexts to the questions

1 - Consume
===
> 1. When testing in real environment, there will be multiple messages flowing through the brokers/topics. How can zerocode validate/asset a specific response?

2 - Produce (and Consume)
===

> 2. Can the producer send a message with a unique ID and the consumer can assert the message with the same ID?

Can we separate these out to two issues for clarity?

**Comment by nirmalchandra** [comment]
> Thanks for the pointers above, guys.
> 
> **1. Can the producer send a message with a unique ID and the consumer can assert the message with the same ID?**
> __Are you referring to the unique message's ID which is the key of the record or are you thinking about consumer client.id ?_
> 
> Both are easy and possible. Just trying to understand your use-case before providing solution or an example._
> 
> **Pretty much both. Use case goes like this:
> 
> We want to test this in a real environment(it could be pre-prod/prod), that means we expect this tool to identify the test messages among the other traffic within kafka brokers
> If there are heaps of messages already flowing through and if we run zerocode to assert one particular message in the pool/topic, will it work ? Does zerocode magically map the response message for a particular test scenario to assert ?
> If yes, how ?**

Let's go this way. First solve the `client.id` uniqueness.
> **Pretty much both. Use case goes like this:

Ans:
`client.id=awesome_producer_${RANDOM.ID}`

That means, everytime the test runs it creates a new unique `client.id` and produces the record.
e.g.
```
1st run - 	client.id = awesome_producer_1553209530873
2nd run - 	client.id = awesome_producer_1553209530889
3rd run - 	client.id = awesome_producer_1553209530893
```
This suffixed numeric ID is never repeated, because it is the numeric equivalent of the current timestamp.

Also you can do via another approach. Suppose you want to make the `client.id` unique per day basis, which means you want to produce all records today with a single `client.id`, but tomorrow with another `client.id`, you can do via the below method.

`client.id=awesome_producer_${LOCAL.DATE.TODAY:yyyy-MM-dd}`
e.g.
```
1st day - 	client.id = awesome_producer_2018-03-18
2nd day - 	client.id = awesome_producer_2018-03-19
3rd day - 	client.id = awesome_producer_2018-03-20
```

Basically you can make it up using various [place holders](https://github.com/authorjapps/zerocode#localdate-and-localdatetime-format-example) explained in the README file to match your project requirement.

Ok. Now let's jump to 2nd part of the question.
It works simillar way. To keep the `key` uniqueness, you can do below
```
"records":[
                    {
                        "key": "id_${RANDOM.NUMBER}", 
                        "value": "Hello World"
                    }
]
```
Also visit [here](https://github.com/authorjapps/zerocode#general-place-holders) for other flavours of uniqueness, which you can pick.

***

Now coming to the last part of the questions

Let's first set the basics right.

+ The consumer can read from an offset it had last committed, unless it is forced to jump or seek to another offset.
+ On the otherhand If it is consuming first time, then it should consume from the beginning.

This part sounds like the 2nd question, which can be addressed in #222.

Am I missing something here?

**Comment by tghani93** [comment]
Thats awesome help, mate. 

1. Where do we assign client.id? Is it a zerocode config ?
2. Does this client.id get translated to kafka consumer group ?

**Comment by nirmalchandra** [comment]
> Thats awesome help, mate.

_It's a pleasure mate. Glad to know._
We have to help each other. Also we hope you see you as a contributor going ahead. 👍 

> 
> 1. Where do we assign client.id? Is it a zerocode config ?
>    I assigned it in kafka_producer.properties to be:

That's correct. You've done it right. It's Kakfa config, not zerocode config. It goes in the `kafka_producer.properties` file.

> 
> client.id=zerocode-producer_${RANDOM.ID}
> 
> But I am not getting it in the log:
> 
> `client.id = zerocode-producer_${RANDOM.ID}`

You got it right. It's in the release pipeline. Will be with you by this weekend(tomorrow), unless it's super urgent for you. If so we can try to get this released by today.

My curiosity to know here is how a uniqueness in `client.id` helps you, unless you are using it for monitoring purpose? Well, that's fine to keep it unique - does no harm anyways, makes the producing clean, makes the tracing easier for later stages of any issues encountered. _How does it helps in testing I mean?_

> 
> 1. Does this client.id get translated to kafka consumer group ?

No. The `group.id` goes in the `kafka_consumer.properties`. Again this is a Kafka config and  Kafka expects this way. You can pick any example and see this already configured
e.g. `group.id=consumerGroup14` etc.

Now, making this unique will help you to achieve your `end to end` testing right(imho). Also, this will enable in rerunning your entire test Suite/Pack i.e. making your CI build pipeline repeatable. I think you might have got the point now, otherwise, I am happy to bring up a Wiki Page to explain this aspect of testing.

Also I was wondering how come you missed this `group.id` point in your original question?

#### Note-
The uniqueness of `group.id` in the similar fashion is also in the release pipeline for tomorrow.

**Comment by authorjapps** [comment]
> `client.id = zerocode-producer_${RANDOM.ID}`
> 

Please use
```xml
<dependency>
  <groupId>org.jsmart</groupId>
  <artifactId>zerocode-tdd</artifactId>
  <version>1.3.5</version>
</dependency>
```

**Comment by tghani93** [comment]
Hi @authorjapps, thanks a ton for pointers. I have added the dependency and ran the test couple of more times but I am still getting `	client.id = zerocode-producer_${RANDOM.ID}`in the log instead of ID.

**Comment by authorjapps** [comment]
Please let us know in case you still facing issues.

**Comment by authorjapps** [comment]
Hey @tghani93, Hope you are doing great mate! We are looking for some feedback on the Kafka usecases and improvements etc? Would you be able to help us 🙏 ? 

Appreciate if you could join [Zerocode Slack(Click)](https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzYxMDAwNTQ3MjY1LTA2YmJjODJhNzQ4ZjBiYTQwZDBmZmNkNmExYjA3ZDk2OGFiZWFmNWJlNGRkOTdiMDQ4ZmQyNzcyNzVjNWQ4ODQ) for a brief chat.
