### ISSUE TITLE
How to pass environment variables in JSON

### ISSUE THREAD

**Issue by bc-nikhil** [authorjapps/zerocode#282]
Please suggest how to pass environment variables in JSON.
The scenario is I want to pass credentials from Jenkins as an environment variables.

**Comment by santhoshTpixler** [comment]
WRT #248 you can access the System properties like **${SYSTEM.PROP:host}**. But are you sure you want to use the environment variables? 
We would be happy to know more about your requirement.

**Comment by vkjha2000** [comment]
@bc-nikhil , I would suggest please put some clarity(bit more details) around your question. 

This will help everyone here and you might get an answer quicker(otherwise we keep on guessing your use-case and we might have to do a `detective` job here to get to the bottom of the issue).

Please visit this guidelines page : 
https://github.com/authorjapps/zerocode/wiki/Guidelines-for-raising-issues

**Comment by bc-nikhil** [comment]
Hi,
Thanks for your reply

Currently, I am using credentials from properties file but I want to store
these credentials in Jenkins job.
So the problem is if I make these credentials as environment variables then
how do I define them for auth token API in JSON file?
As of now I am using credentials from properties So I defined in this
manner in JSON:
$web.application.user1.username
$web.application.user1.password

**Comment by santhoshTpixler** [comment]
@bc-nikhil  At present, we do not have support for fetching the environment variables. Only system properties are supported. We will provide it soon.

**Comment by bc-mahesh** [comment]
We can pass system properties into scenario JSON definitions? Like can I use this -

web.username=SYSTEM.prop.username
web.password=SYSTEM.prop.password

The whole purpose of my question is that I don't want to hardcode the credentials in my JSON files, I need a way to pass those externally, so that anyone having access to the testing codebase won't see them.

**Comment by santhoshTpixler** [comment]
@bc-mahesh You can use `${SYSTEM.PROP:username}` in you JSON which will be resolved to the System property **username**. But make sure you set the System property with `-Dusername=myuser` as an argument while running tests.

**Comment by authorjapps** [comment]
Available in `version 1.3.12` and higher.
