### ISSUE TITLE
Can we start Kafka consumer before the producer

### ISSUE THREAD

**Issue by PrabaharanK** [authorjapps/zerocode#342]
In my scenario, My Kafka consumer not receiving the messages from the topic. After analyse, I get that producer completion takes before consumer start. 

I try to enable auto.offset.rest to "earliest" but I'm afraid it will pick the messages from start. I believe the topic contains more than 100K messages in it. Consuming it all every time is kind of overloading my consumer step.

After googling I get, Start your consumer before producing the message solves the problem. Question is, Is that possible in Zero code ? Appreciate if any alternate approaches to handle the scenario.

**Comment by jneate** [comment]
@PrabaharanK - If your Kafka instance remains active i.e. you don't re-build it between tests then you can use the Kafka consumer-group functionality in combination with the `auto.offset.reset=earliest` config.

This means that when your consumer starts up again, provided the value for `group.id` hasn't changed then your Kafka instance should re-attach the new consumer to the existing group and start processing records that were produced after the last message consumed by the group.

The downside to this is that if this is the first time you're using the consumer group (i.e. creating a new one) then it will read all 100K messages as the `auto.offset.reset` flag is set to "earliest", the solution to that would be to set the `auto.offset.reset` to `latest` and this will mark the consumer group as having consumed all messages in the topic meaning you will have to re-produce any data for the consumer group to pick it up.

Once the consume group is correctly set then it won't matter the order of anything as the consumer will detect it has a set of messages waiting to be consumed since it was last active.

Note that `auto.offset.reset` is only used if no offset is found for the consumer, this means that it's usually only used the first time you consume from a topic.

References:
Group ID: https://docs.confluent.io/current/clients/consumer.html#group-configuration
Offset Management: https://docs.confluent.io/current/clients/consumer.html#id1

**Comment by PrabaharanK** [comment]
okay but in every kafka consume operation we (zero code) are rebuilding the kafka instance right ? I can see KafkaReceiver#receive method has following lines 

`Consumer consumer = KafkaConsumerHelper.createConsumer(kafkaServers, this.consumerPropertyFile, topicName); 
`
and loading auto.offset.reset=latest every time. Still the consumer start from groups last offset position or wait for the new message ? in my case it seems consumer is waiting.
