### ISSUE TITLE
Upgrade the libraries and make it compatible with Java8

### ISSUE THREAD

**Issue by authorjapps** [authorjapps/zerocode#607]
AC:
Upgrade the dependant libraries to their latest compatible version with Java8.

This seems like a pre-req or a good excersize before switching to Java17.

- - - - 
Some work already has been done by @baulea .

Hello @baulea , can you please put the ticket/issue details and PR details in the comments for everyone's visibility?

**Comment by chaitanya1607** [comment]
Can I take this up

**Comment by baulea** [comment]
> AC: Upgrade the dependant libraries to their latest compatible version with Java8.
> 
> This seems like a pre-req or a good excersize before switching to Java17.
> 
> Some work already has been done by @baulea .
> 
> Hello @baulea , can you please put the ticket/issue details and PR details in the comments for everyone's visibility?

Yes, I will soon provide the PR, probably on Sunday.

**Comment by baulea** [comment]
I created the following pull request
#609 

The PR includes the following:

- consolidate maven plugins:
  - Move maven plugin versions and configuration to <pluginManagement> section in parent.pom. 
  - Upgrade maven plugin versions
  - Fix warnings during maven build regarding missing version for maven-compiler-plugin
- upgrade dependencies in pom.xml:
  - upgrade org.jukito:jukito from 1.4.1 to 1.5
  - upgrade commons-io:commons-io:2.4 to 2.15.0
  - upgrade com.aventstack:extentreports:4.0.9 to 5.0.9
  - upgrade com.google.code.gson:gson:2.6.2 to 2.10.1
  - upgrade com.google.protobuf:protobuf-java:3.13.0 to 3.24.4

- with upgrade com.aventstack:extentreports:4.0.9 to 5.0.9 replace ExtentHtmlReporter with ExtentSparkReporter in ExtentReportsFactory.java

- change in core/pom.xml:
  - set test scope for org.jukito:jukito
  - remove unused dependency com.fasterxml.jackson.datatype:jackson-datatype-jdk8
  - remove direct dependency ch.qos.logback:logback-core, because it is a direct dependency from ch.qos.logback:logback-classic
  - add direct dependency org.apache.httpcomponents:httpmime:4.5.12

- change in kafka-testing/pom.xml:
  - remove com.google.protobuf:protobuf-java-util
  - remove dependency for com.github.os72:protoc-jar

**Comment by baulea** [comment]
Hi @authorjapps, is there anything else I should do? Or are we just waiting for a reviewer to review the PR #609 ?

**Comment by baulea** [comment]
As suggested by @a1shadows in https://github.com/authorjapps/zerocode/pull/609 I'll have a look at some more dependencies and try an upgrade.
